"""empty message

Revision ID: 13643102f7a3
Revises: fe0a6f7b710d
Create Date: 2019-07-22 06:51:22.898279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13643102f7a3'
down_revision = 'fe0a6f7b710d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greetings', sa.Column('greeting', sa.String(length=256), nullable=True))
    op.drop_column('greetings', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greetings', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('greetings', 'greeting')
    # ### end Alembic commands ###
